# Generated by Django 5.2 on 2025-05-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerroDetector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('estado', models.CharField(choices=[('En progreso', 'En progreso'), ('Certificado', 'Certificado')], max_length=50)),
            ],
        ),
    ]
