# Generated by Django 5.2 on 2025-05-22 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdiestradorAgricola', '0001_initial'),
        ('PerroDetector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('resultado', models.CharField(max_length=255)),
                ('adiestrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdiestradorAgricola.adiestradoragricola')),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PerroDetector.perrodetector')),
            ],
        ),
    ]
